const PRODUCTS=[
 {id:'ride-car',name:'Happy Ride Car',category:'Ride Ons',age:'1–4 Years',price:1299,old:1699,rating:4.8,tag:'Bestseller',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuByMkc_8bhNBPl-narzAZBruFxol2x1d3z9OytkpOwOcUXr5YqWV3rFJVkQ8Y_7dlg8X4CT906pX3hNbC2t4gW4HW7h03cX0XXpXlR0NhXIk7SOlMkcTCivfVk0gd4Bxz8uMumFZgvhouLLB6NxEBCH9DQ5oI-TMo8Jcv-wnkfAzFb64KuhqwKoiW9go0qCbDDCgDbGl56I-8iYmcdi9WaHkZ9P9TDPzeECjk6peMaOA-i_QrNKFs-PqOGhuqDkWihwBq4'},
 {id:'rings',name:'Rainbow Stacking Rings',category:'Educational',age:'6+ Months',price:499,old:699,rating:4.7,tag:'Top Rated',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuC2OhvNZPNZrqhJdo2IVW3utDFoRzCUt0wbDZAAlRAkvZ-gnDo8o9dunljm8a81ULX-l10NT0QHwF-sWol5wCU8l_jr2HkK-0INrBuKU2dRUxgGwFdkvcjilaqTzA1NTKYViwOyXMD-w08L-QgPICZvxDsw9k9TPcPlX7scjENNduzt8wZs1PcCJRu6B376Fj9ZixJSFu5YumIxRtAWfGwkUSX8YlfukadvaD4gpVURoL7wee2PL0DaXgiBCf9caMS2tFw'},
 {id:'teddy',name:'Soft Teddy Bear',category:'Soft Toys',age:'All Ages',price:699,old:999,rating:4.9,tag:'Loved',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuCqCx1m_BTsGiVNZ3tNMZFux1xRNLrpnLSmNVUPR6zQfeDKNANK2Ndyd8OjK6k6aQSApLb3sVaYYGV6AmbiGKRxeuvQ1A8KK0Wqdj7WI0tGzRILrOq_abVJ_bt0F4IhGjVM6iY_QsyAaWx0k2j3UzaUWXbKH1bdIj5z2L8IViM-Ktsf-U4VqinuMbiYWiNx_NyB0viaJEzAF6o64PMA7gJEejzrYwEZM2nkMt7Oxz16mVfcV-3qs2zIRcSwHc0HnEV_hHY'},
 {id:'monster',name:'RC Monster Truck',category:'Remote Control',age:'6+ Years',price:1499,old:1999,rating:4.6,tag:'New',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuBbWexWKPoUfoVk-oL6cZKXWauR8fiH24qHrYYbOkVPHA3dfUi0J51FufwBv6HjvKp0wkT0n5NvrpUzxlT9bQVbFxJ-9HWnA3Ysut6KGr5JyfnJ3spB22clogZwlwdd0W6uUQPaCTAhvJw2hxmat-Smu8l3IKzCKdOtxyVkiCxGir4uQ0pHwUuXPygXkuHgX70DNtZixMKpboAliTEA3n4YZnns8rmtBMyorMPfaJjIpI3wLzYyPfYXBH5WUmsE2tRu-0k'},
 {id:'blocks',name:'Building Blocks Set',category:'Educational',age:'6+ Years',price:799,old:1049,rating:4.8,tag:'STEM Pick',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuAfryTCkrAE33FJe7UC0peB7sHKgo2bNYpCmqIk7NPARMzhTMbZC7bfJoSTUMEcOc-_QWh6UyjjkzNGf73ynuIH5VqwQUkxQhl9wlJS2UZ7sJ4SLXadfdy6W62MQToR8RR5cusc_-ZFnr9sP79eHtPUMs_GSgs7Q8xNnMZ9LD0z0tDriW6zXSA65o60cK0zvzBBKLF5rACMjcR5TTzXSkYZd7lz8fysy1U7S739qmjqVeDgVI7LHTB7Icj34E6uZu8GzP4'},
 {id:'dino',name:'Dinosaur Toy Set',category:'Action Figures',age:'3+ Years',price:999,old:1399,rating:4.7,tag:'Popular',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuB1n506PEY0mIje1NswMgr15NYHYBRgCTbyi0gDA0CjgygVeRlApgU8cLEOW9JBhu3Cm5YqldDKE_gG8zjU_nv4aum-zWXcba3JL-xcC85jhElxvcCHn8RVEBk45lVBJv6k4BjY1W8Ecxa_h2rOzEFXK5UBH9ooLBEqUm63yCQ40JmJT6sUs3ObPAhRCidqVQbaMLQgoZKL1ZoDPfD4qY3Fg_k5YQIftAi40kZ52Ze1E-pIu95dBSvaOehRkeCAvTMJSVk'},
 {id:'truck',name:'Construction Truck Set',category:'Vehicle Toys',age:'3+ Years',price:899,old:1199,rating:4.5,tag:'25% Off',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuCM3dhgKHPqr_OXzvt6IzpzR3l1SPDvcZ2IfKii-Y13UrnoTHVZVJyklmcRnjlRBgCNG0jRECniy739ujGVm7wvgsaIX97qFPZI_SH5ZpapiAZ5RyrqWDJEsumTsvip0a5Jy_EtWe4BqstBTJR6Qug6QQgttKT55-kUl9-daJCHPcsBTOk75BlhYZdgsDzQHus3z1f51rm2xIj2c21PHyaQB7_PROUCJi67EXYod0HWJNLrph5rga3IdfCv9c254eA0Wzs'},
 {id:'bike',name:'Mini Sports Bike',category:'Ride Ons',age:'3+ Years',price:1499,old:1999,rating:4.6,tag:'Fast Seller',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuDYbdMGn1giVkC9YwZ9FSITvtPrBfFUG7ko9dCLX-UH4Qlvz9Mo2IzpckmwaF_UxJEI6PygsYu43DdndEpUMhvvfO1pw_l-ngpGJd6mDRgmJMgmoBAjjYuO5I1UgEfQ_OYTjxaM-6YOZTYyJWOSY7Ybectma0vUcejRtil3zx0xcO8f9Nx4vKAoTziS8g23a3T4wRs0vzliNVkhyUbrc6vjiuKTjxvY0Ojl6jsLWJ5cKoJMVPp0CNorS7P-3oV3UJbbj1k'},
 {id:'kitchen',name:'Kitchen Play Set',category:'Pretend Play',age:'3+ Years',price:1799,old:2499,rating:4.8,tag:'28% Off',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuACXYhn12Upr8wJTB8m72j_nUc-Y5Sw-GuYhlR9Dv0Q-pc_JYuyKhfHLl6t1LXITYLDR7NfjiOSs2r1Lou3caV77DYDUl4pt6T8ksB3zpDn5hjxKmgW4zhCN-2L-dXWLOFE8PkwWkKfHvEydOKnEp_98kKWOlQHCVqDrgi1rAS8kcR71pHHl8YFo0oZer8oNzVgiNl-CgpsFoQYQ0Dovt2Q8DegPwyNfBQ0FuVFRHztXxhRqQMHbHp9YpRaWnzB9-bXRWI'}
];
const money=n=>'₹'+Number(n).toLocaleString('en-IN');
const getCart=()=>JSON.parse(localStorage.getItem('playjoy-cart')||'{}');
const saveCart=c=>{localStorage.setItem('playjoy-cart',JSON.stringify(c));updateBadges()};
function addProduct(id,qty=1){const c=getCart();c[id]=(c[id]||0)+qty;saveCart(c);toast(`${PRODUCTS.find(p=>p.id===id)?.name||'Toy'} added to cart`)}
function cartCount(){return Object.values(getCart()).reduce((a,b)=>a+b,0)}
function updateBadges(){document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=cartCount())}
function toast(message){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
function productCard(p){const off=Math.round((1-p.price/p.old)*100);return `<article class="product-card reveal" data-category="${p.category}"><span class="tag">${p.tag}</span><button class="heart" aria-label="Add ${p.name} to wishlist" onclick="this.classList.toggle('active');this.textContent=this.classList.contains('active')?'♥':'♡'">♡</button><a href="product_details.html?id=${p.id}" class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"></a><h3><a href="product_details.html?id=${p.id}">${p.name}</a></h3><div class="age">${p.category} · ${p.age}</div><div class="rating">★★★★★ <span style="color:#7b8798">${p.rating}</span></div><div><span class="price">${money(p.price)}</span><span class="old-price">${money(p.old)}</span><span class="discount">${off}% OFF</span></div><div class="product-actions"><button class="btn btn-primary btn-sm" onclick="addProduct('${p.id}')">🛒 Add to Cart</button><button class="icon-btn" onclick="location.href='product_details.html?id=${p.id}'">→</button></div></article>`}
function spritePosition(p){const i=Math.max(0,PRODUCTS.findIndex(x=>x.id===p.id));return `${(i%3)*50}% ${Math.floor(i/3)*50}%`}
productCard=function(p){const off=Math.round((1-p.price/p.old)*100);return `<article class="product-card reveal" data-category="${p.category}"><span class="tag">${p.tag}</span><button class="heart" aria-label="Add ${p.name} to wishlist" onclick="this.classList.toggle('active');this.textContent=this.classList.contains('active')?'♥':'♡'">♡</button><a href="product_details.html?id=${p.id}" class="product-image product-sprite" style="background-position:${spritePosition(p)}" role="img" aria-label="${p.name}"></a><h3><a href="product_details.html?id=${p.id}">${p.name}</a></h3><div class="age">${p.category} · ${p.age}</div><div class="rating">★★★★★ <span style="color:#7b8798">${p.rating}</span></div><div><span class="price">${money(p.price)}</span><span class="old-price">${money(p.old)}</span><span class="discount">${off}% OFF</span></div><div class="product-actions"><button class="btn btn-primary btn-sm" onclick="addProduct('${p.id}')">🛒 Add to Cart</button><button class="icon-btn" onclick="location.href='product_details.html?id=${p.id}'">→</button></div></article>`}
function siteHeader(active=''){return `<div class="topbar"><div class="container"><span>India's Trusted Toy Manufacturer &nbsp; | &nbsp; Pan India Delivery &nbsp; | &nbsp; Safe, Non-Toxic, Durable</span><span class="right"><a href="get_a_sample.html">Become a Distributor</a> &nbsp; | &nbsp; Help</span></div></div><header class="header"><div class="container head-main"><a class="logo" href="index.html"><span>P</span><span>l</span><span>a</span><span>yJoy</span><small>Small Toys. Big Smiles.</small></a><div class="search"><input id="globalSearch" placeholder="Search for toys, categories, or brands..." aria-label="Search products"><button onclick="goSearch()">⌕</button></div><div class="head-actions"><a href="account.html">♙ <span class="label">Login / Register</span></a><a href="shop.html">♡ <span class="label">Wishlist</span></a><a href="cart.html">🛒 <span class="label">Cart</span> <b class="cart-badge" data-cart-count>0</b></a></div><button class="mobile-toggle" onclick="document.querySelector('.nav').classList.toggle('open')">☰</button></div><nav class="container nav"><a class="${active==='shop'?'active':''}" href="shop.html">All Products</a><a href="shop.html?category=Educational">Educational Toys</a><a href="shop.html?category=Ride%20Ons">Ride Ons</a><a href="shop.html?category=Soft%20Toys">Soft Toys</a><a href="shop.html?sort=new">New Arrivals</a><a href="shop.html?sort=rating">Best Sellers</a><a class="${active==='b2b'?'active':''}" href="get_a_sample.html">Bulk Enquiry</a><a class="${active==='about'?'active':''}" href="about.html">Our Story</a></nav></header>`}
function siteFooter(){return `<section class="feature-strip"><div class="container feature-grid"><div class="feature"><span class="ico">🛡️</span><div><b>Safe for Children</b><small>Non-toxic & BIS compliant</small></div></div><div class="feature"><span class="ico">💎</span><div><b>High-Quality Material</b><small>Built to last</small></div></div><div class="feature"><span class="ico">🚚</span><div><b>Pan India Delivery</b><small>Fast & reliable</small></div></div><div class="feature"><span class="ico">🔒</span><div><b>Secure Payments</b><small>100% safe</small></div></div></div></section><footer class="footer"><div class="container footer-grid"><div><a class="logo" href="index.html"><span>P</span><span>l</span><span>a</span><span>yJoy</span><small>Small Toys. Big Smiles.</small></a><p style="color:#6c788d;font-size:13px;max-width:260px">A proud Indian toy manufacturer creating safe, imaginative play for brighter tomorrows.</p></div><div><h4>Shop</h4><a href="shop.html">All Products</a><a href="shop.html?sort=new">New Arrivals</a><a href="shop.html?sort=rating">Best Sellers</a><a href="cart.html">My Cart</a></div><div><h4>B2B</h4><a href="get_a_sample.html">Get a Sample</a><a href="get_a_sample.html">Bulk Enquiry</a><a href="get_a_sample.html">Become a Distributor</a><a href="admin_panel.html">B2B Dashboard</a></div><div><h4>Company</h4><a href="about.html">About Us</a><a href="contact.html">Contact</a><a href="contact.html#faq">FAQs</a><a href="account.html">My Account</a></div></div><div class="container footer-bottom"><span>© 2026 PlayJoy Toys. All rights reserved.</span><span>Terms & Conditions · Privacy Policy · Sitemap</span></div></footer>`}
function goSearch(){const q=document.querySelector('#globalSearch')?.value.trim();location.href='shop.html'+(q?'?q='+encodeURIComponent(q):'')}
function initShell(){document.querySelectorAll('[data-site-header]').forEach(x=>x.innerHTML=siteHeader(x.dataset.siteHeader));document.querySelectorAll('[data-site-footer]').forEach(x=>x.innerHTML=siteFooter());updateBadges();document.querySelector('#globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')goSearch()});const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>io.observe(x))}
document.addEventListener('DOMContentLoaded',initShell);
