const PRODUCTS=[
 {id:'ride-car',name:'Happy Ride Car',category:'Ride Ons',age:'1–4 Years',price:1299,old:1699,rating:4.8,tag:'Bestseller',image:'assets/images/products/happy_ride_car.png'},
 {id:'rings',name:'Rainbow Stacking Rings',category:'Educational',age:'6+ Months',price:499,old:699,rating:4.7,tag:'Top Rated',image:'assets/images/products/rainbow_stacking_rings.png'},
 {id:'teddy',name:'Soft Teddy Bear',category:'Soft Toys',age:'All Ages',price:699,old:999,rating:4.9,tag:'Loved',image:'assets/images/products/soft_teddy_bear.png'},
 {id:'monster',name:'RC Monster Truck',category:'Remote Control',age:'6+ Years',price:1499,old:1999,rating:4.6,tag:'New',image:'assets/images/products/rc_monster_truck.png'},
 {id:'blocks',name:'Building Blocks Set',category:'Educational',age:'6+ Years',price:799,old:1049,rating:4.8,tag:'STEM Pick',image:'assets/images/products/building_blocks_set.png'},
 {id:'dino',name:'Dinosaur Toy Set',category:'Action Figures',age:'3+ Years',price:999,old:1399,rating:4.7,tag:'Popular',image:'assets/images/products/dinosaur_toy_set.png'},
 {id:'truck',name:'Construction Truck Set',category:'Vehicle Toys',age:'3+ Years',price:899,old:1199,rating:4.5,tag:'25% Off',image:'assets/images/products/construction_truck_set.png'},
 {id:'bike',name:'Mini Sports Bike',category:'Ride Ons',age:'3+ Years',price:1499,old:1999,rating:4.6,tag:'Fast Seller',image:'assets/images/products/mini_sports_bike.png'},
 {id:'kitchen',name:'Kitchen Play Set',category:'Pretend Play',age:'3+ Years',price:1799,old:2499,rating:4.8,tag:'28% Off',image:'assets/images/products/kitchen_play_set.png'}
];
const money=n=>'₹'+Number(n).toLocaleString('en-IN');
const getCart=()=>JSON.parse(localStorage.getItem('playjoy-cart')||'{}');
const saveCart=c=>{localStorage.setItem('playjoy-cart',JSON.stringify(c));updateBadges()};
function addProduct(id,qty=1){const c=getCart();c[id]=(c[id]||0)+qty;saveCart(c);toast(`${PRODUCTS.find(p=>p.id===id)?.name||'Toy'} added to cart`)}
function cartCount(){return Object.values(getCart()).reduce((a,b)=>a+b,0)}
function updateBadges(){document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=cartCount())}
function toast(message){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
function productCard(p){const off=Math.round((1-p.price/p.old)*100);return `<article class="product-card reveal" data-category="${p.category}"><span class="tag">${p.tag}</span><button class="heart" aria-label="Add ${p.name} to wishlist" onclick="this.classList.toggle('active');this.innerHTML=this.classList.contains('active')?'&hearts;':'&#9825;'">&#9825;</button><a href="product_details.html?id=${p.id}" class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"></a><h3><a href="product_details.html?id=${p.id}">${p.name}</a></h3><div class="age">${p.category} · ${p.age}</div><div class="rating">★★★★★ <span style="color:#7b8798">${p.rating}</span></div><div><span class="price">${money(p.price)}</span><span class="old-price">${money(p.old)}</span><span class="discount">${off}% OFF</span></div><div class="product-actions"><button class="btn btn-primary btn-sm" onclick="addProduct('${p.id}')"><svg style="width:14px;height:14px;display:inline-block;vertical-align:-2px;margin-right:4px" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>Add to Cart</button><button class="icon-btn" onclick="location.href='product_details.html?id=${p.id}'">→</button></div></article>`}
function siteHeader(active=''){return `<div class="topbar"><div class="container"><span>India's Trusted Toy Manufacturer &nbsp; | &nbsp; Pan India Delivery &nbsp; | &nbsp; Safe, Non-Toxic, Durable</span><span class="right"><a href="get_a_sample.html">Become a Distributor</a> &nbsp; | &nbsp; Help</span></div></div><header class="header"><div class="container head-main"><a class="logo" href="index.html"><span>P</span><span>l</span><span>a</span><span>yJoy</span><small>Small Toys. Big Smiles.</small></a><div class="search"><input id="globalSearch" placeholder="Search for toys, categories, or brands..." aria-label="Search products"><button onclick="goSearch()">⌕</button></div><div class="head-actions"><a href="account.html"><svg style="width:15px;height:15px;display:inline-block;vertical-align:-2px;margin-right:2px" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg> <span class="label">Login / Register</span></a><a href="shop.html"><svg style="width:15px;height:15px;display:inline-block;vertical-align:-2px;margin-right:2px" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg> <span class="label">Wishlist</span></a><a href="cart.html"><svg style="width:15px;height:15px;display:inline-block;vertical-align:-2px;margin-right:2px" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg> <span class="label">Cart</span> <b class="cart-badge" data-cart-count>0</b></a></div><button class="mobile-toggle" onclick="document.querySelector('.nav').classList.toggle('open')">☰</button></div><nav class="container nav"><a class="${active==='shop'?'active':''}" href="shop.html">All Products</a><a href="shop.html?category=Educational">Educational Toys</a><a href="shop.html?category=Ride%20Ons">Ride Ons</a><a href="shop.html?category=Soft%20Toys">Soft Toys</a><a href="shop.html?sort=new">New Arrivals</a><a href="shop.html?sort=rating">Best Sellers</a><a class="${active==='b2b'?'active':''}" href="get_a_sample.html">Bulk Enquiry</a><a class="${active==='about'?'active':''}" href="about.html">Our Story</a></nav></header>`}
function siteFooter(){return `<section class="feature-strip"><div class="container feature-grid"><div class="feature"><span class="ico"><svg style="width:24px;height:24px;color:#0fa958" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg></span><div><b>Safe for Children</b><small>Non-toxic & BIS compliant</small></div></div><div class="feature"><span class="ico"><svg style="width:24px;height:24px;color:#1877e8" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 3h12l4 6-10 12L2 9l4-6z"></path></svg></span><div><b>High-Quality Material</b><small>Built to last</small></div></div><div class="feature"><span class="ico"><svg style="width:24px;height:24px;color:#ff9823" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="1" y="3" width="15" height="13"></rect><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"></polygon><circle cx="5.5" cy="18.5" r="2.5"></circle><circle cx="18.5" cy="18.5" r="2.5"></circle></svg></span><div><b>Pan India Delivery</b><small>Fast & reliable</small></div></div><div class="feature"><span class="ico"><svg style="width:24px;height:24px;color:#e90062" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg></span><div><b>Secure Payments</b><small>100% safe</small></div></div></div></section><footer class="footer"><div class="container footer-grid"><div><a class="logo" href="index.html"><span>P</span><span>l</span><span>a</span><span>yJoy</span><small>Small Toys. Big Smiles.</small></a><p style="color:#6c788d;font-size:13px;max-width:260px">A proud Indian toy manufacturer creating safe, imaginative play for brighter tomorrows.</p></div><div><h4>Shop</h4><a href="shop.html">All Products</a><a href="shop.html?sort=new">New Arrivals</a><a href="shop.html?sort=rating">Best Sellers</a><a href="cart.html">My Cart</a></div><div><h4>B2B</h4><a href="get_a_sample.html">Get a Sample</a><a href="get_a_sample.html">Bulk Enquiry</a><a href="get_a_sample.html">Become a Distributor</a><a href="admin_panel.html">B2B Dashboard</a></div><div><h4>Company</h4><a href="about.html">About Us</a><a href="contact.html">Contact</a><a href="contact.html#faq">FAQs</a><a href="account.html">My Account</a></div></div><div class="container footer-bottom"><span>© 2026 PlayJoy Toys. All rights reserved.</span><span>Terms & Conditions · Privacy Policy · Sitemap</span></div></footer>`}
function goSearch(){const q=document.querySelector('#globalSearch')?.value.trim();location.href='shop.html'+(q?'?q='+encodeURIComponent(q):'')}
function initShell(){document.querySelectorAll('[data-site-header]').forEach(x=>x.innerHTML=siteHeader(x.dataset.siteHeader));document.querySelectorAll('[data-site-footer]').forEach(x=>x.innerHTML=siteFooter());updateBadges();document.querySelector('#globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')goSearch()});const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>io.observe(x))}
document.addEventListener('DOMContentLoaded',initShell);
